# Generated by Django 4.0.3 on 2022-05-09 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instant_messaging', '0003_messagegroup_message_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagegroup',
            name='users',
            field=models.ManyToManyField(blank=True, default=list, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
