# Generated by Django 4.0.3 on 2022-05-09 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instant_messaging', '0004_alter_messagegroup_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagegroup',
            name='users',
            field=models.ManyToManyField(default=list, to=settings.AUTH_USER_MODEL),
        ),
    ]
