# Generated by Django 4.0.3 on 2022-05-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_messaging', '0005_alter_messagegroup_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagegroup',
            name='last_received_message',
            field=models.TextField(default='last msg received!'),
            preserve_default=False,
        ),
    ]
