# Generated by Django 4.0.3 on 2022-05-12 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instant_messaging', '0006_messagegroup_last_received_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagegroup',
            name='last_received_message',
        ),
    ]
