# Generated by Django 4.0.3 on 2022-05-12 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instant_messaging', '0007_remove_messagegroup_last_received_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagegroup',
            name='last_received_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instant_messaging.message'),
        ),
    ]
