# Generated by Django 4.0.5 on 2022-06-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_messaging', '0008_messagegroup_last_received_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_by_recipient',
            field=models.BooleanField(default=False),
        ),
    ]
