# Generated by Django 3.2.7 on 2021-12-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='screen_name',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
