# Generated by Django 3.2 on 2021-07-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowing',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='userfollowing',
            name='unique_followers',
        ),
        migrations.AlterField(
            model_name='userfollowing',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
