# Generated by Django 3.2.7 on 2022-01-31 00:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_userprofile_blocked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='blocked_users',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='blocked_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
