# Generated by Django 3.2 on 2021-07-07 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210707_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='followed_at',
            new_name='followed_on',
        ),
    ]
