# Generated by Django 3.2.7 on 2022-02-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_blocked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, to='accounts.UserProfile'),
        ),
    ]
