# Generated by Django 3.2 on 2021-08-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userfollowing_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowing',
            name='followed_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='%m/%d/%y %H:%M:%S'),
        ),
    ]
