# Generated by Django 3.2 on 2021-08-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userfollowing_followed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowing',
            name='followed_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
