# Generated by Django 4.0.3 on 2022-04-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.ImageField(default='avatars/default.webp', upload_to='avatars/'),
        ),
    ]
