# Generated by Django 3.2.7 on 2021-11-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20211130_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.CharField(max_length=50),
        ),
    ]
