# Generated by Django 4.0.2 on 2022-04-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='post_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
