# Generated by Django 3.0.3 on 2021-04-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediasite', '0002_remove_post_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postID', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
