# Generated by Django 3.0.3 on 2021-04-07 20:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediasite', '0003_postcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='postID',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='socialmediasite.Post'),
            preserve_default=False,
        ),
    ]
