# Generated by Django 3.0.3 on 2021-04-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediasite', '0004_auto_20210407_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={},
        ),
    ]
