# Generated by Django 3.2 on 2021-04-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediasite', '0007_auto_20210410_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='username',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
