# Generated by Django 3.2 on 2021-04-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediasite', '0008_postcomment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
