# Generated by Django 3.2 on 2021-05-16 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediasite', '0009_post_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image_URL', models.TextField()),
                ('date', models.TextField()),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='socialmediasite.post')),
            ],
        ),
    ]
