# Generated by Django 3.2 on 2021-05-30 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediasite', '0011_alter_fight_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='socialmediasite.fight'),
        ),
    ]
