# Generated by Django 3.2 on 2021-05-30 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediasite', '0012_alter_post_fight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='socialmediasite.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='fight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='socialmediasite.fight'),
            preserve_default=False,
        ),
    ]
