# Generated by Django 3.2 on 2021-05-30 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediasite', '0013_auto_20210530_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='socialmediasite.post'),
        ),
    ]
