# Generated by Django 3.2 on 2021-05-30 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediasite', '0014_alter_fight_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fight',
            name='posts',
        ),
        migrations.AlterField(
            model_name='post',
            name='fight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='socialmediasite.fight'),
        ),
    ]
