# Generated by Django 3.2 on 2021-06-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediasite', '0016_fight_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
