# Generated by Django 3.2 on 2021-08-10 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediasite', '0018_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fight',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='socialmediasite.fight'),
        ),
    ]
