# Generated by Django 3.2 on 2021-08-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediasite', '0021_alter_post_fight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='%m/%d/%y %H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='%m/%d/%y %H:%M:%S'),
        ),
    ]
