# Generated by Django 3.2 on 2021-09-14 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fights', '0001_initial'),
        ('socialmediasite', '0026_auto_20210911_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='fights.fight'),
        ),
        migrations.DeleteModel(
            name='Fight',
        ),
    ]
