# Generated by Django 3.2.7 on 2021-11-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image_URL', models.TextField()),
                ('result', models.TextField()),
                ('date', models.TextField()),
            ],
        ),
    ]
