# Generated by Django 4.0.2 on 2022-04-05 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postentities_post_entities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postentities',
            old_name='user_mentions',
            new_name='mentioned_users',
        ),
    ]
