# Generated by Django 3.2.7 on 2021-10-17 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210930_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.postcomment'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='username',
            field=models.TextField(blank=True),
        ),
    ]
