# Generated by Django 4.0.3 on 2022-04-18 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_content_repost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repost',
            old_name='date_reposted',
            new_name='date',
        ),
    ]
