# Generated by Django 4.0.2 on 2022-04-05 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentEntities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentioned_users', models.ManyToManyField(blank=True, related_name='comment_user_mentions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='postcomment',
            name='entities',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_entities', to='post_comments.commententities'),
            preserve_default=False,
        ),
    ]
