# Generated by Django 4.0.2 on 2022-04-05 23:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_comments', '0002_commententities_postcomment_entities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentEntities',
            new_name='PostCommentEntities',
        ),
    ]
